### ISSUE TITLE
Question: auto lock after system start

### ISSUE THREAD

**Issue by marwenbk** [temaivanoff/flutter-lock-task#2]
Hello
Thanks for the great work
is there a way to automatically launch the app after device start or reboot?
rebooting the device will allow the user to exit the app
Thanks

**Comment by marwenbk** [comment]
# Flutter App Auto-Start on Boot (Kotlin)

This guide demonstrates how to configure an Android Flutter app to automatically start when the device boots, using a custom `BroadcastReceiver` in Kotlin.

## Step 1: Add Permissions

Modify your `AndroidManifest.xml` by adding the following permission inside the `<manifest>` tag:

```xml
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
```

## Step 2: Create a BroadcastReceiver in Kotlin

Create a file named `BootReceiver.kt` in the directory `your_project/android/app/src/main/kotlin/your/package/name/` (replace `your/package/name` with your actual package name). Add the following Kotlin code:

```kotlin
package your.package.name

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent

class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (Intent.ACTION_BOOT_COMPLETED == intent.action) {
            val i = Intent(context, MainActivity::class.java)
            i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(i)
        }
    }
}
```

## Step 3: Update MainActivity.kt

Ensure your `MainActivity.kt` is correctly set up to launch your Flutter app:

```kotlin
package your.package.name

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        // Your additional setup if needed
    }
}
```

## Step 4: Update AndroidManifest.xml

Register the `BootReceiver` in your `AndroidManifest.xml` file. Add the following inside the `<application>` tag:

```xml
<receiver android:name=".BootReceiver" android:enabled="true" android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"/>
    </intent-filter>
</receiver>
```

## Step 5: Testing

Compile your app and run it at least once. Then, reboot your device to test if the app launches automatically after boot completion.

**Comment by Arpit980jai** [comment]
Hello I have tried to use the above support to launch the app automatically after the the boot completes.
**My Android Manifest File**
`<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.MANAGE_DEVICE_ADMINS" />
    <uses-permission android:name="android.permission.BIND_DEVICE_ADMIN"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <application
        android:label="testappfirst"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <receiver android:name=".BootReceiver" android:enabled="true" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
        <receiver android:exported="true" android:name="flutter.lock.task.flutter_lock_task.DeviceAdmin" android:permission="android.permission.BIND_DEVICE_ADMIN">
            <meta-data android:name="android.app.device_admin" android:resource="@xml/policies" />
            <intent-filter android:exported="true">
                <action android:name="android.app.action.DEVICE_ADMIN_ENABLED" />
                <action android:name="android.app.action.ACTION_DEVICE_ADMIN_DISABLE_REQUESTED" />
                <action android:name="android.app.action.ACTION_DEVICE_ADMIN_DISABLED" />
                <action android:name="android.intent.action.PROFILE_PROVISIONING_COMPLETE"/>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>
`

**Boot Receiver KT file**

`package com.example.testappfirst

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent

class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (Intent.ACTION_BOOT_COMPLETED == intent.action) {
            val i = Intent(context, MainActivity::class.java)
            i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(i)
        }
    }
}`


**MainActivity.kt**

`package com.example.testappfirst

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    // No additional code is needed unless you're customizing behavior.
}
`
